version: 2

project_name: fate

before:
  hooks:
    - go mod tidy

builds:
  - id: fate
    main: ./cmd/console
    binary: fate
    env:
      - CGO_ENABLED=1
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- .Arch }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: babyname
    name: fate
  draft: false
  prerelease: auto
