// Code generated by entc, DO NOT EDIT.

package version

const (
	// Label holds the string label denoting the version type in the database.
	Label = "version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldUpdatedUnix holds the string denoting the updatedunix field in the database.
	FieldUpdatedUnix = "updated_unix"
	// Table holds the table name of the version in the database.
	Table = "versions"
)

// Columns holds all SQL columns for version fields.
var Columns = []string{
	FieldID,
	FieldVersion,
	FieldUpdatedUnix,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
