// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CharactersColumns holds the columns for the "characters" table.
	CharactersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "hash", Type: field.TypeString, Unique: true},
		{Name: "pin_yin", Type: field.TypeJSON},
		{Name: "ch", Type: field.TypeString},
		{Name: "science_stroke", Type: field.TypeInt8},
		{Name: "radical", Type: field.TypeString},
		{Name: "radical_stroke", Type: field.TypeInt8},
		{Name: "stroke", Type: field.TypeInt8},
		{Name: "is_kang_xi", Type: field.TypeBool},
		{Name: "kang_xi", Type: field.TypeString},
		{Name: "kang_xi_stroke", Type: field.TypeString},
		{Name: "simple_radical", Type: field.TypeString},
		{Name: "simple_radical_stroke", Type: field.TypeString},
		{Name: "simple_total_stroke", Type: field.TypeInt8},
		{Name: "traditional_radical", Type: field.TypeString},
		{Name: "traditional_radical_stroke", Type: field.TypeInt8},
		{Name: "traditional_total_stroke", Type: field.TypeInt8},
		{Name: "is_name_science", Type: field.TypeBool},
		{Name: "wu_xing", Type: field.TypeString},
		{Name: "lucky", Type: field.TypeString},
		{Name: "is_regular", Type: field.TypeBool},
		{Name: "traditional_character", Type: field.TypeJSON},
		{Name: "variant_character", Type: field.TypeJSON},
		{Name: "comment", Type: field.TypeString, Size: 2147483647},
	}
	// CharactersTable holds the schema information for the "characters" table.
	CharactersTable = &schema.Table{
		Name:        "characters",
		Columns:     CharactersColumns,
		PrimaryKey:  []*schema.Column{CharactersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CharactersTable,
	}
)

func init() {
}
