// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/babyname/fate/ent/ncharacter"
)

// NCharacterCreate is the builder for creating a NCharacter entity.
type NCharacterCreate struct {
	config
	mutation *NCharacterMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPinYin sets the "pin_yin" field.
func (nc *NCharacterCreate) SetPinYin(s string) *NCharacterCreate {
	nc.mutation.SetPinYin(s)
	return nc
}

// SetChID sets the "ch_id" field.
func (nc *NCharacterCreate) SetChID(i int64) *NCharacterCreate {
	nc.mutation.SetChID(i)
	return nc
}

// SetCh sets the "ch" field.
func (nc *NCharacterCreate) SetCh(s string) *NCharacterCreate {
	nc.mutation.SetCh(s)
	return nc
}

// SetRadical sets the "radical" field.
func (nc *NCharacterCreate) SetRadical(s string) *NCharacterCreate {
	nc.mutation.SetRadical(s)
	return nc
}

// SetRadicalStroke sets the "radical_stroke" field.
func (nc *NCharacterCreate) SetRadicalStroke(i int) *NCharacterCreate {
	nc.mutation.SetRadicalStroke(i)
	return nc
}

// SetTotalStroke sets the "total_stroke" field.
func (nc *NCharacterCreate) SetTotalStroke(i int) *NCharacterCreate {
	nc.mutation.SetTotalStroke(i)
	return nc
}

// SetIsKangXi sets the "is_kang_xi" field.
func (nc *NCharacterCreate) SetIsKangXi(b bool) *NCharacterCreate {
	nc.mutation.SetIsKangXi(b)
	return nc
}

// SetRelateKangXi sets the "relate_kang_xi" field.
func (nc *NCharacterCreate) SetRelateKangXi(s string) *NCharacterCreate {
	nc.mutation.SetRelateKangXi(s)
	return nc
}

// SetRelateSimple sets the "relate_simple" field.
func (nc *NCharacterCreate) SetRelateSimple(s string) *NCharacterCreate {
	nc.mutation.SetRelateSimple(s)
	return nc
}

// SetRelateTraditional sets the "relate_traditional" field.
func (nc *NCharacterCreate) SetRelateTraditional(s string) *NCharacterCreate {
	nc.mutation.SetRelateTraditional(s)
	return nc
}

// SetRelateVariant sets the "relate_variant" field.
func (nc *NCharacterCreate) SetRelateVariant(s string) *NCharacterCreate {
	nc.mutation.SetRelateVariant(s)
	return nc
}

// SetNameScience sets the "name_science" field.
func (nc *NCharacterCreate) SetNameScience(b bool) *NCharacterCreate {
	nc.mutation.SetNameScience(b)
	return nc
}

// SetScienceStroke sets the "science_stroke" field.
func (nc *NCharacterCreate) SetScienceStroke(i int) *NCharacterCreate {
	nc.mutation.SetScienceStroke(i)
	return nc
}

// SetWuXing sets the "wu_xing" field.
func (nc *NCharacterCreate) SetWuXing(s string) *NCharacterCreate {
	nc.mutation.SetWuXing(s)
	return nc
}

// SetLucky sets the "lucky" field.
func (nc *NCharacterCreate) SetLucky(s string) *NCharacterCreate {
	nc.mutation.SetLucky(s)
	return nc
}

// SetRegular sets the "regular" field.
func (nc *NCharacterCreate) SetRegular(b bool) *NCharacterCreate {
	nc.mutation.SetRegular(b)
	return nc
}

// SetComment sets the "comment" field.
func (nc *NCharacterCreate) SetComment(s string) *NCharacterCreate {
	nc.mutation.SetComment(s)
	return nc
}

// SetID sets the "id" field.
func (nc *NCharacterCreate) SetID(s string) *NCharacterCreate {
	nc.mutation.SetID(s)
	return nc
}

// Mutation returns the NCharacterMutation object of the builder.
func (nc *NCharacterCreate) Mutation() *NCharacterMutation {
	return nc.mutation
}

// Save creates the NCharacter in the database.
func (nc *NCharacterCreate) Save(ctx context.Context) (*NCharacter, error) {
	return withHooks(ctx, nc.sqlSave, nc.mutation, nc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NCharacterCreate) SaveX(ctx context.Context) *NCharacter {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nc *NCharacterCreate) Exec(ctx context.Context) error {
	_, err := nc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nc *NCharacterCreate) ExecX(ctx context.Context) {
	if err := nc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nc *NCharacterCreate) check() error {
	if _, ok := nc.mutation.PinYin(); !ok {
		return &ValidationError{Name: "pin_yin", err: errors.New(`ent: missing required field "NCharacter.pin_yin"`)}
	}
	if _, ok := nc.mutation.ChID(); !ok {
		return &ValidationError{Name: "ch_id", err: errors.New(`ent: missing required field "NCharacter.ch_id"`)}
	}
	if _, ok := nc.mutation.Ch(); !ok {
		return &ValidationError{Name: "ch", err: errors.New(`ent: missing required field "NCharacter.ch"`)}
	}
	if _, ok := nc.mutation.Radical(); !ok {
		return &ValidationError{Name: "radical", err: errors.New(`ent: missing required field "NCharacter.radical"`)}
	}
	if _, ok := nc.mutation.RadicalStroke(); !ok {
		return &ValidationError{Name: "radical_stroke", err: errors.New(`ent: missing required field "NCharacter.radical_stroke"`)}
	}
	if _, ok := nc.mutation.TotalStroke(); !ok {
		return &ValidationError{Name: "total_stroke", err: errors.New(`ent: missing required field "NCharacter.total_stroke"`)}
	}
	if _, ok := nc.mutation.IsKangXi(); !ok {
		return &ValidationError{Name: "is_kang_xi", err: errors.New(`ent: missing required field "NCharacter.is_kang_xi"`)}
	}
	if _, ok := nc.mutation.RelateKangXi(); !ok {
		return &ValidationError{Name: "relate_kang_xi", err: errors.New(`ent: missing required field "NCharacter.relate_kang_xi"`)}
	}
	if _, ok := nc.mutation.RelateSimple(); !ok {
		return &ValidationError{Name: "relate_simple", err: errors.New(`ent: missing required field "NCharacter.relate_simple"`)}
	}
	if _, ok := nc.mutation.RelateTraditional(); !ok {
		return &ValidationError{Name: "relate_traditional", err: errors.New(`ent: missing required field "NCharacter.relate_traditional"`)}
	}
	if _, ok := nc.mutation.RelateVariant(); !ok {
		return &ValidationError{Name: "relate_variant", err: errors.New(`ent: missing required field "NCharacter.relate_variant"`)}
	}
	if _, ok := nc.mutation.NameScience(); !ok {
		return &ValidationError{Name: "name_science", err: errors.New(`ent: missing required field "NCharacter.name_science"`)}
	}
	if _, ok := nc.mutation.ScienceStroke(); !ok {
		return &ValidationError{Name: "science_stroke", err: errors.New(`ent: missing required field "NCharacter.science_stroke"`)}
	}
	if _, ok := nc.mutation.WuXing(); !ok {
		return &ValidationError{Name: "wu_xing", err: errors.New(`ent: missing required field "NCharacter.wu_xing"`)}
	}
	if _, ok := nc.mutation.Lucky(); !ok {
		return &ValidationError{Name: "lucky", err: errors.New(`ent: missing required field "NCharacter.lucky"`)}
	}
	if _, ok := nc.mutation.Regular(); !ok {
		return &ValidationError{Name: "regular", err: errors.New(`ent: missing required field "NCharacter.regular"`)}
	}
	if _, ok := nc.mutation.Comment(); !ok {
		return &ValidationError{Name: "comment", err: errors.New(`ent: missing required field "NCharacter.comment"`)}
	}
	return nil
}

func (nc *NCharacterCreate) sqlSave(ctx context.Context) (*NCharacter, error) {
	if err := nc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected NCharacter.ID type: %T", _spec.ID.Value)
		}
	}
	nc.mutation.id = &_node.ID
	nc.mutation.done = true
	return _node, nil
}

func (nc *NCharacterCreate) createSpec() (*NCharacter, *sqlgraph.CreateSpec) {
	var (
		_node = &NCharacter{config: nc.config}
		_spec = sqlgraph.NewCreateSpec(ncharacter.Table, sqlgraph.NewFieldSpec(ncharacter.FieldID, field.TypeString))
	)
	_spec.OnConflict = nc.conflict
	if id, ok := nc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := nc.mutation.PinYin(); ok {
		_spec.SetField(ncharacter.FieldPinYin, field.TypeString, value)
		_node.PinYin = value
	}
	if value, ok := nc.mutation.ChID(); ok {
		_spec.SetField(ncharacter.FieldChID, field.TypeInt64, value)
		_node.ChID = value
	}
	if value, ok := nc.mutation.Ch(); ok {
		_spec.SetField(ncharacter.FieldCh, field.TypeString, value)
		_node.Ch = value
	}
	if value, ok := nc.mutation.Radical(); ok {
		_spec.SetField(ncharacter.FieldRadical, field.TypeString, value)
		_node.Radical = value
	}
	if value, ok := nc.mutation.RadicalStroke(); ok {
		_spec.SetField(ncharacter.FieldRadicalStroke, field.TypeInt, value)
		_node.RadicalStroke = value
	}
	if value, ok := nc.mutation.TotalStroke(); ok {
		_spec.SetField(ncharacter.FieldTotalStroke, field.TypeInt, value)
		_node.TotalStroke = value
	}
	if value, ok := nc.mutation.IsKangXi(); ok {
		_spec.SetField(ncharacter.FieldIsKangXi, field.TypeBool, value)
		_node.IsKangXi = value
	}
	if value, ok := nc.mutation.RelateKangXi(); ok {
		_spec.SetField(ncharacter.FieldRelateKangXi, field.TypeString, value)
		_node.RelateKangXi = value
	}
	if value, ok := nc.mutation.RelateSimple(); ok {
		_spec.SetField(ncharacter.FieldRelateSimple, field.TypeString, value)
		_node.RelateSimple = value
	}
	if value, ok := nc.mutation.RelateTraditional(); ok {
		_spec.SetField(ncharacter.FieldRelateTraditional, field.TypeString, value)
		_node.RelateTraditional = value
	}
	if value, ok := nc.mutation.RelateVariant(); ok {
		_spec.SetField(ncharacter.FieldRelateVariant, field.TypeString, value)
		_node.RelateVariant = value
	}
	if value, ok := nc.mutation.NameScience(); ok {
		_spec.SetField(ncharacter.FieldNameScience, field.TypeBool, value)
		_node.NameScience = value
	}
	if value, ok := nc.mutation.ScienceStroke(); ok {
		_spec.SetField(ncharacter.FieldScienceStroke, field.TypeInt, value)
		_node.ScienceStroke = value
	}
	if value, ok := nc.mutation.WuXing(); ok {
		_spec.SetField(ncharacter.FieldWuXing, field.TypeString, value)
		_node.WuXing = value
	}
	if value, ok := nc.mutation.Lucky(); ok {
		_spec.SetField(ncharacter.FieldLucky, field.TypeString, value)
		_node.Lucky = value
	}
	if value, ok := nc.mutation.Regular(); ok {
		_spec.SetField(ncharacter.FieldRegular, field.TypeBool, value)
		_node.Regular = value
	}
	if value, ok := nc.mutation.Comment(); ok {
		_spec.SetField(ncharacter.FieldComment, field.TypeString, value)
		_node.Comment = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NCharacter.Create().
//		SetPinYin(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NCharacterUpsert) {
//			SetPinYin(v+v).
//		}).
//		Exec(ctx)
func (nc *NCharacterCreate) OnConflict(opts ...sql.ConflictOption) *NCharacterUpsertOne {
	nc.conflict = opts
	return &NCharacterUpsertOne{
		create: nc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NCharacter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (nc *NCharacterCreate) OnConflictColumns(columns ...string) *NCharacterUpsertOne {
	nc.conflict = append(nc.conflict, sql.ConflictColumns(columns...))
	return &NCharacterUpsertOne{
		create: nc,
	}
}

type (
	// NCharacterUpsertOne is the builder for "upsert"-ing
	//  one NCharacter node.
	NCharacterUpsertOne struct {
		create *NCharacterCreate
	}

	// NCharacterUpsert is the "OnConflict" setter.
	NCharacterUpsert struct {
		*sql.UpdateSet
	}
)

// SetPinYin sets the "pin_yin" field.
func (u *NCharacterUpsert) SetPinYin(v string) *NCharacterUpsert {
	u.Set(ncharacter.FieldPinYin, v)
	return u
}

// UpdatePinYin sets the "pin_yin" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdatePinYin() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldPinYin)
	return u
}

// SetChID sets the "ch_id" field.
func (u *NCharacterUpsert) SetChID(v int64) *NCharacterUpsert {
	u.Set(ncharacter.FieldChID, v)
	return u
}

// UpdateChID sets the "ch_id" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateChID() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldChID)
	return u
}

// AddChID adds v to the "ch_id" field.
func (u *NCharacterUpsert) AddChID(v int64) *NCharacterUpsert {
	u.Add(ncharacter.FieldChID, v)
	return u
}

// SetCh sets the "ch" field.
func (u *NCharacterUpsert) SetCh(v string) *NCharacterUpsert {
	u.Set(ncharacter.FieldCh, v)
	return u
}

// UpdateCh sets the "ch" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateCh() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldCh)
	return u
}

// SetRadical sets the "radical" field.
func (u *NCharacterUpsert) SetRadical(v string) *NCharacterUpsert {
	u.Set(ncharacter.FieldRadical, v)
	return u
}

// UpdateRadical sets the "radical" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateRadical() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldRadical)
	return u
}

// SetRadicalStroke sets the "radical_stroke" field.
func (u *NCharacterUpsert) SetRadicalStroke(v int) *NCharacterUpsert {
	u.Set(ncharacter.FieldRadicalStroke, v)
	return u
}

// UpdateRadicalStroke sets the "radical_stroke" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateRadicalStroke() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldRadicalStroke)
	return u
}

// AddRadicalStroke adds v to the "radical_stroke" field.
func (u *NCharacterUpsert) AddRadicalStroke(v int) *NCharacterUpsert {
	u.Add(ncharacter.FieldRadicalStroke, v)
	return u
}

// SetTotalStroke sets the "total_stroke" field.
func (u *NCharacterUpsert) SetTotalStroke(v int) *NCharacterUpsert {
	u.Set(ncharacter.FieldTotalStroke, v)
	return u
}

// UpdateTotalStroke sets the "total_stroke" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateTotalStroke() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldTotalStroke)
	return u
}

// AddTotalStroke adds v to the "total_stroke" field.
func (u *NCharacterUpsert) AddTotalStroke(v int) *NCharacterUpsert {
	u.Add(ncharacter.FieldTotalStroke, v)
	return u
}

// SetIsKangXi sets the "is_kang_xi" field.
func (u *NCharacterUpsert) SetIsKangXi(v bool) *NCharacterUpsert {
	u.Set(ncharacter.FieldIsKangXi, v)
	return u
}

// UpdateIsKangXi sets the "is_kang_xi" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateIsKangXi() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldIsKangXi)
	return u
}

// SetRelateKangXi sets the "relate_kang_xi" field.
func (u *NCharacterUpsert) SetRelateKangXi(v string) *NCharacterUpsert {
	u.Set(ncharacter.FieldRelateKangXi, v)
	return u
}

// UpdateRelateKangXi sets the "relate_kang_xi" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateRelateKangXi() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldRelateKangXi)
	return u
}

// SetRelateSimple sets the "relate_simple" field.
func (u *NCharacterUpsert) SetRelateSimple(v string) *NCharacterUpsert {
	u.Set(ncharacter.FieldRelateSimple, v)
	return u
}

// UpdateRelateSimple sets the "relate_simple" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateRelateSimple() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldRelateSimple)
	return u
}

// SetRelateTraditional sets the "relate_traditional" field.
func (u *NCharacterUpsert) SetRelateTraditional(v string) *NCharacterUpsert {
	u.Set(ncharacter.FieldRelateTraditional, v)
	return u
}

// UpdateRelateTraditional sets the "relate_traditional" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateRelateTraditional() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldRelateTraditional)
	return u
}

// SetRelateVariant sets the "relate_variant" field.
func (u *NCharacterUpsert) SetRelateVariant(v string) *NCharacterUpsert {
	u.Set(ncharacter.FieldRelateVariant, v)
	return u
}

// UpdateRelateVariant sets the "relate_variant" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateRelateVariant() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldRelateVariant)
	return u
}

// SetNameScience sets the "name_science" field.
func (u *NCharacterUpsert) SetNameScience(v bool) *NCharacterUpsert {
	u.Set(ncharacter.FieldNameScience, v)
	return u
}

// UpdateNameScience sets the "name_science" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateNameScience() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldNameScience)
	return u
}

// SetScienceStroke sets the "science_stroke" field.
func (u *NCharacterUpsert) SetScienceStroke(v int) *NCharacterUpsert {
	u.Set(ncharacter.FieldScienceStroke, v)
	return u
}

// UpdateScienceStroke sets the "science_stroke" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateScienceStroke() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldScienceStroke)
	return u
}

// AddScienceStroke adds v to the "science_stroke" field.
func (u *NCharacterUpsert) AddScienceStroke(v int) *NCharacterUpsert {
	u.Add(ncharacter.FieldScienceStroke, v)
	return u
}

// SetWuXing sets the "wu_xing" field.
func (u *NCharacterUpsert) SetWuXing(v string) *NCharacterUpsert {
	u.Set(ncharacter.FieldWuXing, v)
	return u
}

// UpdateWuXing sets the "wu_xing" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateWuXing() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldWuXing)
	return u
}

// SetLucky sets the "lucky" field.
func (u *NCharacterUpsert) SetLucky(v string) *NCharacterUpsert {
	u.Set(ncharacter.FieldLucky, v)
	return u
}

// UpdateLucky sets the "lucky" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateLucky() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldLucky)
	return u
}

// SetRegular sets the "regular" field.
func (u *NCharacterUpsert) SetRegular(v bool) *NCharacterUpsert {
	u.Set(ncharacter.FieldRegular, v)
	return u
}

// UpdateRegular sets the "regular" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateRegular() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldRegular)
	return u
}

// SetComment sets the "comment" field.
func (u *NCharacterUpsert) SetComment(v string) *NCharacterUpsert {
	u.Set(ncharacter.FieldComment, v)
	return u
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *NCharacterUpsert) UpdateComment() *NCharacterUpsert {
	u.SetExcluded(ncharacter.FieldComment)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NCharacter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ncharacter.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NCharacterUpsertOne) UpdateNewValues() *NCharacterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ncharacter.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NCharacter.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NCharacterUpsertOne) Ignore() *NCharacterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NCharacterUpsertOne) DoNothing() *NCharacterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NCharacterCreate.OnConflict
// documentation for more info.
func (u *NCharacterUpsertOne) Update(set func(*NCharacterUpsert)) *NCharacterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NCharacterUpsert{UpdateSet: update})
	}))
	return u
}

// SetPinYin sets the "pin_yin" field.
func (u *NCharacterUpsertOne) SetPinYin(v string) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetPinYin(v)
	})
}

// UpdatePinYin sets the "pin_yin" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdatePinYin() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdatePinYin()
	})
}

// SetChID sets the "ch_id" field.
func (u *NCharacterUpsertOne) SetChID(v int64) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetChID(v)
	})
}

// AddChID adds v to the "ch_id" field.
func (u *NCharacterUpsertOne) AddChID(v int64) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.AddChID(v)
	})
}

// UpdateChID sets the "ch_id" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateChID() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateChID()
	})
}

// SetCh sets the "ch" field.
func (u *NCharacterUpsertOne) SetCh(v string) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetCh(v)
	})
}

// UpdateCh sets the "ch" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateCh() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateCh()
	})
}

// SetRadical sets the "radical" field.
func (u *NCharacterUpsertOne) SetRadical(v string) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRadical(v)
	})
}

// UpdateRadical sets the "radical" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateRadical() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRadical()
	})
}

// SetRadicalStroke sets the "radical_stroke" field.
func (u *NCharacterUpsertOne) SetRadicalStroke(v int) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRadicalStroke(v)
	})
}

// AddRadicalStroke adds v to the "radical_stroke" field.
func (u *NCharacterUpsertOne) AddRadicalStroke(v int) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.AddRadicalStroke(v)
	})
}

// UpdateRadicalStroke sets the "radical_stroke" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateRadicalStroke() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRadicalStroke()
	})
}

// SetTotalStroke sets the "total_stroke" field.
func (u *NCharacterUpsertOne) SetTotalStroke(v int) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetTotalStroke(v)
	})
}

// AddTotalStroke adds v to the "total_stroke" field.
func (u *NCharacterUpsertOne) AddTotalStroke(v int) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.AddTotalStroke(v)
	})
}

// UpdateTotalStroke sets the "total_stroke" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateTotalStroke() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateTotalStroke()
	})
}

// SetIsKangXi sets the "is_kang_xi" field.
func (u *NCharacterUpsertOne) SetIsKangXi(v bool) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetIsKangXi(v)
	})
}

// UpdateIsKangXi sets the "is_kang_xi" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateIsKangXi() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateIsKangXi()
	})
}

// SetRelateKangXi sets the "relate_kang_xi" field.
func (u *NCharacterUpsertOne) SetRelateKangXi(v string) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRelateKangXi(v)
	})
}

// UpdateRelateKangXi sets the "relate_kang_xi" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateRelateKangXi() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRelateKangXi()
	})
}

// SetRelateSimple sets the "relate_simple" field.
func (u *NCharacterUpsertOne) SetRelateSimple(v string) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRelateSimple(v)
	})
}

// UpdateRelateSimple sets the "relate_simple" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateRelateSimple() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRelateSimple()
	})
}

// SetRelateTraditional sets the "relate_traditional" field.
func (u *NCharacterUpsertOne) SetRelateTraditional(v string) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRelateTraditional(v)
	})
}

// UpdateRelateTraditional sets the "relate_traditional" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateRelateTraditional() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRelateTraditional()
	})
}

// SetRelateVariant sets the "relate_variant" field.
func (u *NCharacterUpsertOne) SetRelateVariant(v string) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRelateVariant(v)
	})
}

// UpdateRelateVariant sets the "relate_variant" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateRelateVariant() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRelateVariant()
	})
}

// SetNameScience sets the "name_science" field.
func (u *NCharacterUpsertOne) SetNameScience(v bool) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetNameScience(v)
	})
}

// UpdateNameScience sets the "name_science" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateNameScience() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateNameScience()
	})
}

// SetScienceStroke sets the "science_stroke" field.
func (u *NCharacterUpsertOne) SetScienceStroke(v int) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetScienceStroke(v)
	})
}

// AddScienceStroke adds v to the "science_stroke" field.
func (u *NCharacterUpsertOne) AddScienceStroke(v int) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.AddScienceStroke(v)
	})
}

// UpdateScienceStroke sets the "science_stroke" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateScienceStroke() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateScienceStroke()
	})
}

// SetWuXing sets the "wu_xing" field.
func (u *NCharacterUpsertOne) SetWuXing(v string) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetWuXing(v)
	})
}

// UpdateWuXing sets the "wu_xing" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateWuXing() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateWuXing()
	})
}

// SetLucky sets the "lucky" field.
func (u *NCharacterUpsertOne) SetLucky(v string) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetLucky(v)
	})
}

// UpdateLucky sets the "lucky" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateLucky() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateLucky()
	})
}

// SetRegular sets the "regular" field.
func (u *NCharacterUpsertOne) SetRegular(v bool) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRegular(v)
	})
}

// UpdateRegular sets the "regular" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateRegular() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRegular()
	})
}

// SetComment sets the "comment" field.
func (u *NCharacterUpsertOne) SetComment(v string) *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetComment(v)
	})
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *NCharacterUpsertOne) UpdateComment() *NCharacterUpsertOne {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateComment()
	})
}

// Exec executes the query.
func (u *NCharacterUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NCharacterCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NCharacterUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NCharacterUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: NCharacterUpsertOne.ID is not supported by MySQL driver. Use NCharacterUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NCharacterUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NCharacterCreateBulk is the builder for creating many NCharacter entities in bulk.
type NCharacterCreateBulk struct {
	config
	err      error
	builders []*NCharacterCreate
	conflict []sql.ConflictOption
}

// Save creates the NCharacter entities in the database.
func (ncb *NCharacterCreateBulk) Save(ctx context.Context) ([]*NCharacter, error) {
	if ncb.err != nil {
		return nil, ncb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ncb.builders))
	nodes := make([]*NCharacter, len(ncb.builders))
	mutators := make([]Mutator, len(ncb.builders))
	for i := range ncb.builders {
		func(i int, root context.Context) {
			builder := ncb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NCharacterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ncb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ncb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ncb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ncb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ncb *NCharacterCreateBulk) SaveX(ctx context.Context) []*NCharacter {
	v, err := ncb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncb *NCharacterCreateBulk) Exec(ctx context.Context) error {
	_, err := ncb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncb *NCharacterCreateBulk) ExecX(ctx context.Context) {
	if err := ncb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NCharacter.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NCharacterUpsert) {
//			SetPinYin(v+v).
//		}).
//		Exec(ctx)
func (ncb *NCharacterCreateBulk) OnConflict(opts ...sql.ConflictOption) *NCharacterUpsertBulk {
	ncb.conflict = opts
	return &NCharacterUpsertBulk{
		create: ncb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NCharacter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ncb *NCharacterCreateBulk) OnConflictColumns(columns ...string) *NCharacterUpsertBulk {
	ncb.conflict = append(ncb.conflict, sql.ConflictColumns(columns...))
	return &NCharacterUpsertBulk{
		create: ncb,
	}
}

// NCharacterUpsertBulk is the builder for "upsert"-ing
// a bulk of NCharacter nodes.
type NCharacterUpsertBulk struct {
	create *NCharacterCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NCharacter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ncharacter.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NCharacterUpsertBulk) UpdateNewValues() *NCharacterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ncharacter.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NCharacter.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NCharacterUpsertBulk) Ignore() *NCharacterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NCharacterUpsertBulk) DoNothing() *NCharacterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NCharacterCreateBulk.OnConflict
// documentation for more info.
func (u *NCharacterUpsertBulk) Update(set func(*NCharacterUpsert)) *NCharacterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NCharacterUpsert{UpdateSet: update})
	}))
	return u
}

// SetPinYin sets the "pin_yin" field.
func (u *NCharacterUpsertBulk) SetPinYin(v string) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetPinYin(v)
	})
}

// UpdatePinYin sets the "pin_yin" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdatePinYin() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdatePinYin()
	})
}

// SetChID sets the "ch_id" field.
func (u *NCharacterUpsertBulk) SetChID(v int64) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetChID(v)
	})
}

// AddChID adds v to the "ch_id" field.
func (u *NCharacterUpsertBulk) AddChID(v int64) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.AddChID(v)
	})
}

// UpdateChID sets the "ch_id" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateChID() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateChID()
	})
}

// SetCh sets the "ch" field.
func (u *NCharacterUpsertBulk) SetCh(v string) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetCh(v)
	})
}

// UpdateCh sets the "ch" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateCh() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateCh()
	})
}

// SetRadical sets the "radical" field.
func (u *NCharacterUpsertBulk) SetRadical(v string) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRadical(v)
	})
}

// UpdateRadical sets the "radical" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateRadical() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRadical()
	})
}

// SetRadicalStroke sets the "radical_stroke" field.
func (u *NCharacterUpsertBulk) SetRadicalStroke(v int) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRadicalStroke(v)
	})
}

// AddRadicalStroke adds v to the "radical_stroke" field.
func (u *NCharacterUpsertBulk) AddRadicalStroke(v int) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.AddRadicalStroke(v)
	})
}

// UpdateRadicalStroke sets the "radical_stroke" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateRadicalStroke() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRadicalStroke()
	})
}

// SetTotalStroke sets the "total_stroke" field.
func (u *NCharacterUpsertBulk) SetTotalStroke(v int) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetTotalStroke(v)
	})
}

// AddTotalStroke adds v to the "total_stroke" field.
func (u *NCharacterUpsertBulk) AddTotalStroke(v int) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.AddTotalStroke(v)
	})
}

// UpdateTotalStroke sets the "total_stroke" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateTotalStroke() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateTotalStroke()
	})
}

// SetIsKangXi sets the "is_kang_xi" field.
func (u *NCharacterUpsertBulk) SetIsKangXi(v bool) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetIsKangXi(v)
	})
}

// UpdateIsKangXi sets the "is_kang_xi" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateIsKangXi() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateIsKangXi()
	})
}

// SetRelateKangXi sets the "relate_kang_xi" field.
func (u *NCharacterUpsertBulk) SetRelateKangXi(v string) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRelateKangXi(v)
	})
}

// UpdateRelateKangXi sets the "relate_kang_xi" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateRelateKangXi() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRelateKangXi()
	})
}

// SetRelateSimple sets the "relate_simple" field.
func (u *NCharacterUpsertBulk) SetRelateSimple(v string) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRelateSimple(v)
	})
}

// UpdateRelateSimple sets the "relate_simple" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateRelateSimple() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRelateSimple()
	})
}

// SetRelateTraditional sets the "relate_traditional" field.
func (u *NCharacterUpsertBulk) SetRelateTraditional(v string) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRelateTraditional(v)
	})
}

// UpdateRelateTraditional sets the "relate_traditional" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateRelateTraditional() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRelateTraditional()
	})
}

// SetRelateVariant sets the "relate_variant" field.
func (u *NCharacterUpsertBulk) SetRelateVariant(v string) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRelateVariant(v)
	})
}

// UpdateRelateVariant sets the "relate_variant" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateRelateVariant() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRelateVariant()
	})
}

// SetNameScience sets the "name_science" field.
func (u *NCharacterUpsertBulk) SetNameScience(v bool) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetNameScience(v)
	})
}

// UpdateNameScience sets the "name_science" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateNameScience() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateNameScience()
	})
}

// SetScienceStroke sets the "science_stroke" field.
func (u *NCharacterUpsertBulk) SetScienceStroke(v int) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetScienceStroke(v)
	})
}

// AddScienceStroke adds v to the "science_stroke" field.
func (u *NCharacterUpsertBulk) AddScienceStroke(v int) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.AddScienceStroke(v)
	})
}

// UpdateScienceStroke sets the "science_stroke" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateScienceStroke() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateScienceStroke()
	})
}

// SetWuXing sets the "wu_xing" field.
func (u *NCharacterUpsertBulk) SetWuXing(v string) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetWuXing(v)
	})
}

// UpdateWuXing sets the "wu_xing" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateWuXing() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateWuXing()
	})
}

// SetLucky sets the "lucky" field.
func (u *NCharacterUpsertBulk) SetLucky(v string) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetLucky(v)
	})
}

// UpdateLucky sets the "lucky" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateLucky() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateLucky()
	})
}

// SetRegular sets the "regular" field.
func (u *NCharacterUpsertBulk) SetRegular(v bool) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetRegular(v)
	})
}

// UpdateRegular sets the "regular" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateRegular() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateRegular()
	})
}

// SetComment sets the "comment" field.
func (u *NCharacterUpsertBulk) SetComment(v string) *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.SetComment(v)
	})
}

// UpdateComment sets the "comment" field to the value that was provided on create.
func (u *NCharacterUpsertBulk) UpdateComment() *NCharacterUpsertBulk {
	return u.Update(func(s *NCharacterUpsert) {
		s.UpdateComment()
	})
}

// Exec executes the query.
func (u *NCharacterUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NCharacterCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NCharacterCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NCharacterUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
