// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/babyname/fate/ent/predicate"
	"github.com/babyname/fate/ent/wugelucky"
)

// WuGeLuckyDelete is the builder for deleting a WuGeLucky entity.
type WuGeLuckyDelete struct {
	config
	hooks    []Hook
	mutation *WuGeLuckyMutation
}

// Where appends a list predicates to the WuGeLuckyDelete builder.
func (wgld *WuGeLuckyDelete) Where(ps ...predicate.WuGeLucky) *WuGeLuckyDelete {
	wgld.mutation.Where(ps...)
	return wgld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wgld *WuGeLuckyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wgld.hooks) == 0 {
		affected, err = wgld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*WuGeLuckyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			wgld.mutation = mutation
			affected, err = wgld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wgld.hooks) - 1; i >= 0; i-- {
			if wgld.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wgld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wgld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (wgld *WuGeLuckyDelete) ExecX(ctx context.Context) int {
	n, err := wgld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wgld *WuGeLuckyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: wugelucky.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: wugelucky.FieldID,
			},
		},
	}
	if ps := wgld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wgld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// WuGeLuckyDeleteOne is the builder for deleting a single WuGeLucky entity.
type WuGeLuckyDeleteOne struct {
	wgld *WuGeLuckyDelete
}

// Exec executes the deletion query.
func (wgldo *WuGeLuckyDeleteOne) Exec(ctx context.Context) error {
	n, err := wgldo.wgld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{wugelucky.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wgldo *WuGeLuckyDeleteOne) ExecX(ctx context.Context) {
	wgldo.wgld.ExecX(ctx)
}
