// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/babyname/fate/ent/predicate"
	"github.com/babyname/fate/ent/wugelucky"
)

// WuGeLuckyQuery is the builder for querying WuGeLucky entities.
type WuGeLuckyQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.WuGeLucky
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WuGeLuckyQuery builder.
func (wglq *WuGeLuckyQuery) Where(ps ...predicate.WuGeLucky) *WuGeLuckyQuery {
	wglq.predicates = append(wglq.predicates, ps...)
	return wglq
}

// Limit adds a limit step to the query.
func (wglq *WuGeLuckyQuery) Limit(limit int) *WuGeLuckyQuery {
	wglq.limit = &limit
	return wglq
}

// Offset adds an offset step to the query.
func (wglq *WuGeLuckyQuery) Offset(offset int) *WuGeLuckyQuery {
	wglq.offset = &offset
	return wglq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wglq *WuGeLuckyQuery) Unique(unique bool) *WuGeLuckyQuery {
	wglq.unique = &unique
	return wglq
}

// Order adds an order step to the query.
func (wglq *WuGeLuckyQuery) Order(o ...OrderFunc) *WuGeLuckyQuery {
	wglq.order = append(wglq.order, o...)
	return wglq
}

// First returns the first WuGeLucky entity from the query.
// Returns a *NotFoundError when no WuGeLucky was found.
func (wglq *WuGeLuckyQuery) First(ctx context.Context) (*WuGeLucky, error) {
	nodes, err := wglq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wugelucky.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wglq *WuGeLuckyQuery) FirstX(ctx context.Context) *WuGeLucky {
	node, err := wglq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WuGeLucky ID from the query.
// Returns a *NotFoundError when no WuGeLucky ID was found.
func (wglq *WuGeLuckyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wglq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wugelucky.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wglq *WuGeLuckyQuery) FirstIDX(ctx context.Context) int {
	id, err := wglq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WuGeLucky entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WuGeLucky entity is found.
// Returns a *NotFoundError when no WuGeLucky entities are found.
func (wglq *WuGeLuckyQuery) Only(ctx context.Context) (*WuGeLucky, error) {
	nodes, err := wglq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wugelucky.Label}
	default:
		return nil, &NotSingularError{wugelucky.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wglq *WuGeLuckyQuery) OnlyX(ctx context.Context) *WuGeLucky {
	node, err := wglq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WuGeLucky ID in the query.
// Returns a *NotSingularError when more than one WuGeLucky ID is found.
// Returns a *NotFoundError when no entities are found.
func (wglq *WuGeLuckyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wglq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wugelucky.Label}
	default:
		err = &NotSingularError{wugelucky.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wglq *WuGeLuckyQuery) OnlyIDX(ctx context.Context) int {
	id, err := wglq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WuGeLuckies.
func (wglq *WuGeLuckyQuery) All(ctx context.Context) ([]*WuGeLucky, error) {
	if err := wglq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return wglq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (wglq *WuGeLuckyQuery) AllX(ctx context.Context) []*WuGeLucky {
	nodes, err := wglq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WuGeLucky IDs.
func (wglq *WuGeLuckyQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := wglq.Select(wugelucky.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wglq *WuGeLuckyQuery) IDsX(ctx context.Context) []int {
	ids, err := wglq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wglq *WuGeLuckyQuery) Count(ctx context.Context) (int, error) {
	if err := wglq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return wglq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (wglq *WuGeLuckyQuery) CountX(ctx context.Context) int {
	count, err := wglq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wglq *WuGeLuckyQuery) Exist(ctx context.Context) (bool, error) {
	if err := wglq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return wglq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (wglq *WuGeLuckyQuery) ExistX(ctx context.Context) bool {
	exist, err := wglq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WuGeLuckyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wglq *WuGeLuckyQuery) Clone() *WuGeLuckyQuery {
	if wglq == nil {
		return nil
	}
	return &WuGeLuckyQuery{
		config:     wglq.config,
		limit:      wglq.limit,
		offset:     wglq.offset,
		order:      append([]OrderFunc{}, wglq.order...),
		predicates: append([]predicate.WuGeLucky{}, wglq.predicates...),
		// clone intermediate query.
		sql:    wglq.sql.Clone(),
		path:   wglq.path,
		unique: wglq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LastStroke1 int `json:"last_stroke_1,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WuGeLucky.Query().
//		GroupBy(wugelucky.FieldLastStroke1).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wglq *WuGeLuckyQuery) GroupBy(field string, fields ...string) *WuGeLuckyGroupBy {
	grbuild := &WuGeLuckyGroupBy{config: wglq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := wglq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return wglq.sqlQuery(ctx), nil
	}
	grbuild.label = wugelucky.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LastStroke1 int `json:"last_stroke_1,omitempty"`
//	}
//
//	client.WuGeLucky.Query().
//		Select(wugelucky.FieldLastStroke1).
//		Scan(ctx, &v)
func (wglq *WuGeLuckyQuery) Select(fields ...string) *WuGeLuckySelect {
	wglq.fields = append(wglq.fields, fields...)
	selbuild := &WuGeLuckySelect{WuGeLuckyQuery: wglq}
	selbuild.label = wugelucky.Label
	selbuild.flds, selbuild.scan = &wglq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a WuGeLuckySelect configured with the given aggregations.
func (wglq *WuGeLuckyQuery) Aggregate(fns ...AggregateFunc) *WuGeLuckySelect {
	return wglq.Select().Aggregate(fns...)
}

func (wglq *WuGeLuckyQuery) prepareQuery(ctx context.Context) error {
	for _, f := range wglq.fields {
		if !wugelucky.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wglq.path != nil {
		prev, err := wglq.path(ctx)
		if err != nil {
			return err
		}
		wglq.sql = prev
	}
	return nil
}

func (wglq *WuGeLuckyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WuGeLucky, error) {
	var (
		nodes = []*WuGeLucky{}
		_spec = wglq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WuGeLucky).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WuGeLucky{config: wglq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wglq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (wglq *WuGeLuckyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wglq.querySpec()
	_spec.Node.Columns = wglq.fields
	if len(wglq.fields) > 0 {
		_spec.Unique = wglq.unique != nil && *wglq.unique
	}
	return sqlgraph.CountNodes(ctx, wglq.driver, _spec)
}

func (wglq *WuGeLuckyQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := wglq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (wglq *WuGeLuckyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   wugelucky.Table,
			Columns: wugelucky.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: wugelucky.FieldID,
			},
		},
		From:   wglq.sql,
		Unique: true,
	}
	if unique := wglq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := wglq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wugelucky.FieldID)
		for i := range fields {
			if fields[i] != wugelucky.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wglq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wglq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wglq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wglq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wglq *WuGeLuckyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wglq.driver.Dialect())
	t1 := builder.Table(wugelucky.Table)
	columns := wglq.fields
	if len(columns) == 0 {
		columns = wugelucky.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wglq.sql != nil {
		selector = wglq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wglq.unique != nil && *wglq.unique {
		selector.Distinct()
	}
	for _, p := range wglq.predicates {
		p(selector)
	}
	for _, p := range wglq.order {
		p(selector)
	}
	if offset := wglq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wglq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WuGeLuckyGroupBy is the group-by builder for WuGeLucky entities.
type WuGeLuckyGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wglgb *WuGeLuckyGroupBy) Aggregate(fns ...AggregateFunc) *WuGeLuckyGroupBy {
	wglgb.fns = append(wglgb.fns, fns...)
	return wglgb
}

// Scan applies the group-by query and scans the result into the given value.
func (wglgb *WuGeLuckyGroupBy) Scan(ctx context.Context, v any) error {
	query, err := wglgb.path(ctx)
	if err != nil {
		return err
	}
	wglgb.sql = query
	return wglgb.sqlScan(ctx, v)
}

func (wglgb *WuGeLuckyGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range wglgb.fields {
		if !wugelucky.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := wglgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wglgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (wglgb *WuGeLuckyGroupBy) sqlQuery() *sql.Selector {
	selector := wglgb.sql.Select()
	aggregation := make([]string, 0, len(wglgb.fns))
	for _, fn := range wglgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(wglgb.fields)+len(wglgb.fns))
		for _, f := range wglgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(wglgb.fields...)...)
}

// WuGeLuckySelect is the builder for selecting fields of WuGeLucky entities.
type WuGeLuckySelect struct {
	*WuGeLuckyQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wgls *WuGeLuckySelect) Aggregate(fns ...AggregateFunc) *WuGeLuckySelect {
	wgls.fns = append(wgls.fns, fns...)
	return wgls
}

// Scan applies the selector query and scans the result into the given value.
func (wgls *WuGeLuckySelect) Scan(ctx context.Context, v any) error {
	if err := wgls.prepareQuery(ctx); err != nil {
		return err
	}
	wgls.sql = wgls.WuGeLuckyQuery.sqlQuery(ctx)
	return wgls.sqlScan(ctx, v)
}

func (wgls *WuGeLuckySelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(wgls.fns))
	for _, fn := range wgls.fns {
		aggregation = append(aggregation, fn(wgls.sql))
	}
	switch n := len(*wgls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		wgls.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		wgls.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := wgls.sql.Query()
	if err := wgls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
