// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/babyname/fate/ent/wugelucky"
	"github.com/google/uuid"
)

// WuGeLuckyCreate is the builder for creating a WuGeLucky entity.
type WuGeLuckyCreate struct {
	config
	mutation *WuGeLuckyMutation
	hooks    []Hook
}

// SetLastStroke1 sets the "last_stroke_1" field.
func (wglc *WuGeLuckyCreate) SetLastStroke1(i int) *WuGeLuckyCreate {
	wglc.mutation.SetLastStroke1(i)
	return wglc
}

// SetLastStroke2 sets the "last_stroke_2" field.
func (wglc *WuGeLuckyCreate) SetLastStroke2(i int) *WuGeLuckyCreate {
	wglc.mutation.SetLastStroke2(i)
	return wglc
}

// SetFirstStroke1 sets the "first_stroke_1" field.
func (wglc *WuGeLuckyCreate) SetFirstStroke1(i int) *WuGeLuckyCreate {
	wglc.mutation.SetFirstStroke1(i)
	return wglc
}

// SetFirstStroke2 sets the "first_stroke_2" field.
func (wglc *WuGeLuckyCreate) SetFirstStroke2(i int) *WuGeLuckyCreate {
	wglc.mutation.SetFirstStroke2(i)
	return wglc
}

// SetTianGe sets the "tian_ge" field.
func (wglc *WuGeLuckyCreate) SetTianGe(i int) *WuGeLuckyCreate {
	wglc.mutation.SetTianGe(i)
	return wglc
}

// SetTianDaYan sets the "tian_da_yan" field.
func (wglc *WuGeLuckyCreate) SetTianDaYan(s string) *WuGeLuckyCreate {
	wglc.mutation.SetTianDaYan(s)
	return wglc
}

// SetRenGe sets the "ren_ge" field.
func (wglc *WuGeLuckyCreate) SetRenGe(i int) *WuGeLuckyCreate {
	wglc.mutation.SetRenGe(i)
	return wglc
}

// SetRenDaYan sets the "ren_da_yan" field.
func (wglc *WuGeLuckyCreate) SetRenDaYan(s string) *WuGeLuckyCreate {
	wglc.mutation.SetRenDaYan(s)
	return wglc
}

// SetDiGe sets the "di_ge" field.
func (wglc *WuGeLuckyCreate) SetDiGe(i int) *WuGeLuckyCreate {
	wglc.mutation.SetDiGe(i)
	return wglc
}

// SetDiDaYan sets the "di_da_yan" field.
func (wglc *WuGeLuckyCreate) SetDiDaYan(s string) *WuGeLuckyCreate {
	wglc.mutation.SetDiDaYan(s)
	return wglc
}

// SetWaiGe sets the "wai_ge" field.
func (wglc *WuGeLuckyCreate) SetWaiGe(i int) *WuGeLuckyCreate {
	wglc.mutation.SetWaiGe(i)
	return wglc
}

// SetWaiDaYan sets the "wai_da_yan" field.
func (wglc *WuGeLuckyCreate) SetWaiDaYan(s string) *WuGeLuckyCreate {
	wglc.mutation.SetWaiDaYan(s)
	return wglc
}

// SetZongGe sets the "zong_ge" field.
func (wglc *WuGeLuckyCreate) SetZongGe(i int) *WuGeLuckyCreate {
	wglc.mutation.SetZongGe(i)
	return wglc
}

// SetZongDaYan sets the "zong_da_yan" field.
func (wglc *WuGeLuckyCreate) SetZongDaYan(s string) *WuGeLuckyCreate {
	wglc.mutation.SetZongDaYan(s)
	return wglc
}

// SetZongLucky sets the "zong_lucky" field.
func (wglc *WuGeLuckyCreate) SetZongLucky(b bool) *WuGeLuckyCreate {
	wglc.mutation.SetZongLucky(b)
	return wglc
}

// SetZongSex sets the "zong_sex" field.
func (wglc *WuGeLuckyCreate) SetZongSex(b bool) *WuGeLuckyCreate {
	wglc.mutation.SetZongSex(b)
	return wglc
}

// SetZongMax sets the "zong_max" field.
func (wglc *WuGeLuckyCreate) SetZongMax(b bool) *WuGeLuckyCreate {
	wglc.mutation.SetZongMax(b)
	return wglc
}

// SetID sets the "id" field.
func (wglc *WuGeLuckyCreate) SetID(u uuid.UUID) *WuGeLuckyCreate {
	wglc.mutation.SetID(u)
	return wglc
}

// Mutation returns the WuGeLuckyMutation object of the builder.
func (wglc *WuGeLuckyCreate) Mutation() *WuGeLuckyMutation {
	return wglc.mutation
}

// Save creates the WuGeLucky in the database.
func (wglc *WuGeLuckyCreate) Save(ctx context.Context) (*WuGeLucky, error) {
	return withHooks[*WuGeLucky, WuGeLuckyMutation](ctx, wglc.sqlSave, wglc.mutation, wglc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wglc *WuGeLuckyCreate) SaveX(ctx context.Context) *WuGeLucky {
	v, err := wglc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wglc *WuGeLuckyCreate) Exec(ctx context.Context) error {
	_, err := wglc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wglc *WuGeLuckyCreate) ExecX(ctx context.Context) {
	if err := wglc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wglc *WuGeLuckyCreate) check() error {
	if _, ok := wglc.mutation.LastStroke1(); !ok {
		return &ValidationError{Name: "last_stroke_1", err: errors.New(`ent: missing required field "WuGeLucky.last_stroke_1"`)}
	}
	if _, ok := wglc.mutation.LastStroke2(); !ok {
		return &ValidationError{Name: "last_stroke_2", err: errors.New(`ent: missing required field "WuGeLucky.last_stroke_2"`)}
	}
	if _, ok := wglc.mutation.FirstStroke1(); !ok {
		return &ValidationError{Name: "first_stroke_1", err: errors.New(`ent: missing required field "WuGeLucky.first_stroke_1"`)}
	}
	if _, ok := wglc.mutation.FirstStroke2(); !ok {
		return &ValidationError{Name: "first_stroke_2", err: errors.New(`ent: missing required field "WuGeLucky.first_stroke_2"`)}
	}
	if _, ok := wglc.mutation.TianGe(); !ok {
		return &ValidationError{Name: "tian_ge", err: errors.New(`ent: missing required field "WuGeLucky.tian_ge"`)}
	}
	if _, ok := wglc.mutation.TianDaYan(); !ok {
		return &ValidationError{Name: "tian_da_yan", err: errors.New(`ent: missing required field "WuGeLucky.tian_da_yan"`)}
	}
	if _, ok := wglc.mutation.RenGe(); !ok {
		return &ValidationError{Name: "ren_ge", err: errors.New(`ent: missing required field "WuGeLucky.ren_ge"`)}
	}
	if _, ok := wglc.mutation.RenDaYan(); !ok {
		return &ValidationError{Name: "ren_da_yan", err: errors.New(`ent: missing required field "WuGeLucky.ren_da_yan"`)}
	}
	if _, ok := wglc.mutation.DiGe(); !ok {
		return &ValidationError{Name: "di_ge", err: errors.New(`ent: missing required field "WuGeLucky.di_ge"`)}
	}
	if _, ok := wglc.mutation.DiDaYan(); !ok {
		return &ValidationError{Name: "di_da_yan", err: errors.New(`ent: missing required field "WuGeLucky.di_da_yan"`)}
	}
	if _, ok := wglc.mutation.WaiGe(); !ok {
		return &ValidationError{Name: "wai_ge", err: errors.New(`ent: missing required field "WuGeLucky.wai_ge"`)}
	}
	if _, ok := wglc.mutation.WaiDaYan(); !ok {
		return &ValidationError{Name: "wai_da_yan", err: errors.New(`ent: missing required field "WuGeLucky.wai_da_yan"`)}
	}
	if _, ok := wglc.mutation.ZongGe(); !ok {
		return &ValidationError{Name: "zong_ge", err: errors.New(`ent: missing required field "WuGeLucky.zong_ge"`)}
	}
	if _, ok := wglc.mutation.ZongDaYan(); !ok {
		return &ValidationError{Name: "zong_da_yan", err: errors.New(`ent: missing required field "WuGeLucky.zong_da_yan"`)}
	}
	if _, ok := wglc.mutation.ZongLucky(); !ok {
		return &ValidationError{Name: "zong_lucky", err: errors.New(`ent: missing required field "WuGeLucky.zong_lucky"`)}
	}
	if _, ok := wglc.mutation.ZongSex(); !ok {
		return &ValidationError{Name: "zong_sex", err: errors.New(`ent: missing required field "WuGeLucky.zong_sex"`)}
	}
	if _, ok := wglc.mutation.ZongMax(); !ok {
		return &ValidationError{Name: "zong_max", err: errors.New(`ent: missing required field "WuGeLucky.zong_max"`)}
	}
	return nil
}

func (wglc *WuGeLuckyCreate) sqlSave(ctx context.Context) (*WuGeLucky, error) {
	if err := wglc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wglc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wglc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	wglc.mutation.id = &_node.ID
	wglc.mutation.done = true
	return _node, nil
}

func (wglc *WuGeLuckyCreate) createSpec() (*WuGeLucky, *sqlgraph.CreateSpec) {
	var (
		_node = &WuGeLucky{config: wglc.config}
		_spec = sqlgraph.NewCreateSpec(wugelucky.Table, sqlgraph.NewFieldSpec(wugelucky.FieldID, field.TypeUUID))
	)
	if id, ok := wglc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := wglc.mutation.LastStroke1(); ok {
		_spec.SetField(wugelucky.FieldLastStroke1, field.TypeInt, value)
		_node.LastStroke1 = value
	}
	if value, ok := wglc.mutation.LastStroke2(); ok {
		_spec.SetField(wugelucky.FieldLastStroke2, field.TypeInt, value)
		_node.LastStroke2 = value
	}
	if value, ok := wglc.mutation.FirstStroke1(); ok {
		_spec.SetField(wugelucky.FieldFirstStroke1, field.TypeInt, value)
		_node.FirstStroke1 = value
	}
	if value, ok := wglc.mutation.FirstStroke2(); ok {
		_spec.SetField(wugelucky.FieldFirstStroke2, field.TypeInt, value)
		_node.FirstStroke2 = value
	}
	if value, ok := wglc.mutation.TianGe(); ok {
		_spec.SetField(wugelucky.FieldTianGe, field.TypeInt, value)
		_node.TianGe = value
	}
	if value, ok := wglc.mutation.TianDaYan(); ok {
		_spec.SetField(wugelucky.FieldTianDaYan, field.TypeString, value)
		_node.TianDaYan = value
	}
	if value, ok := wglc.mutation.RenGe(); ok {
		_spec.SetField(wugelucky.FieldRenGe, field.TypeInt, value)
		_node.RenGe = value
	}
	if value, ok := wglc.mutation.RenDaYan(); ok {
		_spec.SetField(wugelucky.FieldRenDaYan, field.TypeString, value)
		_node.RenDaYan = value
	}
	if value, ok := wglc.mutation.DiGe(); ok {
		_spec.SetField(wugelucky.FieldDiGe, field.TypeInt, value)
		_node.DiGe = value
	}
	if value, ok := wglc.mutation.DiDaYan(); ok {
		_spec.SetField(wugelucky.FieldDiDaYan, field.TypeString, value)
		_node.DiDaYan = value
	}
	if value, ok := wglc.mutation.WaiGe(); ok {
		_spec.SetField(wugelucky.FieldWaiGe, field.TypeInt, value)
		_node.WaiGe = value
	}
	if value, ok := wglc.mutation.WaiDaYan(); ok {
		_spec.SetField(wugelucky.FieldWaiDaYan, field.TypeString, value)
		_node.WaiDaYan = value
	}
	if value, ok := wglc.mutation.ZongGe(); ok {
		_spec.SetField(wugelucky.FieldZongGe, field.TypeInt, value)
		_node.ZongGe = value
	}
	if value, ok := wglc.mutation.ZongDaYan(); ok {
		_spec.SetField(wugelucky.FieldZongDaYan, field.TypeString, value)
		_node.ZongDaYan = value
	}
	if value, ok := wglc.mutation.ZongLucky(); ok {
		_spec.SetField(wugelucky.FieldZongLucky, field.TypeBool, value)
		_node.ZongLucky = value
	}
	if value, ok := wglc.mutation.ZongSex(); ok {
		_spec.SetField(wugelucky.FieldZongSex, field.TypeBool, value)
		_node.ZongSex = value
	}
	if value, ok := wglc.mutation.ZongMax(); ok {
		_spec.SetField(wugelucky.FieldZongMax, field.TypeBool, value)
		_node.ZongMax = value
	}
	return _node, _spec
}

// WuGeLuckyCreateBulk is the builder for creating many WuGeLucky entities in bulk.
type WuGeLuckyCreateBulk struct {
	config
	builders []*WuGeLuckyCreate
}

// Save creates the WuGeLucky entities in the database.
func (wglcb *WuGeLuckyCreateBulk) Save(ctx context.Context) ([]*WuGeLucky, error) {
	specs := make([]*sqlgraph.CreateSpec, len(wglcb.builders))
	nodes := make([]*WuGeLucky, len(wglcb.builders))
	mutators := make([]Mutator, len(wglcb.builders))
	for i := range wglcb.builders {
		func(i int, root context.Context) {
			builder := wglcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WuGeLuckyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wglcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wglcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wglcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wglcb *WuGeLuckyCreateBulk) SaveX(ctx context.Context) []*WuGeLucky {
	v, err := wglcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wglcb *WuGeLuckyCreateBulk) Exec(ctx context.Context) error {
	_, err := wglcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wglcb *WuGeLuckyCreateBulk) ExecX(ctx context.Context) {
	if err := wglcb.Exec(ctx); err != nil {
		panic(err)
	}
}
